# Generated by Django 3.1.3 on 2020-12-13 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='quizUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(choices=[('SAS', 'SAS'), ('SEAS', 'SEAS'), ('NURS', 'Nursing'), ('WHAR', 'Wharton'), ('GRAD', 'Graduate'), ('DEFAULT', 'Default')], default='DEFAULT', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('NEVER', 'Never'), ('ONCE_PM', 'Once/few times per month'), ('ONCE_PW', 'Once/few times per week'), ('EVERYDAY', 'Everyday')], default='NEVER', max_length=10)),
                ('body', models.CharField(default='Default Question', max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.quiz')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizApp.quizuser')),
            ],
        ),
    ]
