# Generated by Django 3.1.3 on 2020-12-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='year_in_school',
            field=models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='Freshman', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='school',
            field=models.CharField(choices=[('SAS', 'SAS'), ('SEAS', 'SEAS'), ('Nursing', 'Nursing'), ('Wharton', 'Wharton'), ('Graduate', 'Graduate'), ('Default', 'Default')], default='Default', max_length=10),
        ),
    ]
