# Generated by Django 3.1.3 on 2020-12-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0002_auto_20201213_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='covidScore',
            field=models.IntegerField(default=0),
        ),
    ]
