# Generated by Django 3.1.3 on 2020-12-13 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0003_quizuser_covidscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizApp.quiz'),
        ),
    ]
