# Generated by Django 3.1.3 on 2020-12-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_auto_20201213_1333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='users',
        ),
    ]
