# Generated by Django 3.1.3 on 2020-12-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0006_auto_20201213_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='users',
        ),
        migrations.AddField(
            model_name='quizuser',
            name='questions',
            field=models.ManyToManyField(to='quizApp.Question'),
        ),
    ]
