# Generated by Django 3.1.3 on 2020-12-13 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0008_auto_20201213_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='quizuser',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizApp.quiz'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('NEVER', 'Never'), ('ONCE_PM', 'Once/few times per month'), ('ONCE_PW', 'Once/few times per week'), ('EVERYDAY', 'Everyday')], default='NEVER', max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApp.quizuser')),
            ],
        ),
    ]
