# Generated by Django 3.1.4 on 2020-12-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0009_auto_20201213_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='userChoice',
            field=models.CharField(choices=[('NEVER', 'Never'), ('ONCE_PM', 'Once/few times per month'), ('ONCE_PW', 'Once/few times per week'), ('EVERYDAY', 'Everyday')], default='NEVER', max_length=10),
        ),
    ]
