# Generated by Django 3.1.4 on 2020-12-14 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0010_response_userchoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='answer',
        ),
    ]
